<?php


namespace App\Http\Helpers;

use Aws\S3\S3Client;
use Aws\S3\Exception\S3Exception;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Intervention\Image\ImageManagerStatic as Image;
use Exception;


final class TestingHelper
{
    private $bucket;
    private $region;
    private $key;
    private $secret;
    private $version;
    private $url;

    const VALID_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp'];

    public function __construct()
    {
        $this->bucket = env('AWS_BUCKET');
        $this->region = env('AWS_DEFAULT_REGION');
        $this->key = env('AWS_ACCESS_KEY_ID');
        $this->secret = env('AWS_SECRET_ACCESS_KEY');
        $this->version = env('AWS_VERSION');
        $this->url = env('AWS_URL');
    }

    public function delete(): bool
    {
        return false;
    }

    public function store($file, $path): bool
    {
        try{
            $entry_path = $this->saveOnLocal($file, $path);
            $webp_path = $this->convertToWebp($entry_path);

            return true;
        }catch(Exception $e){
            Log::error('Error storing file on S3: ' . $path, [
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    public function update(): bool
    {
        return false;
    }


    // private function for save files on local storage
    private function saveOnLocal($file, $path): string
    {
        try{
            # get file extension
            $ext = $file->getClientOriginalExtension();

            // validate if $ext is a valid image extension
            if (!in_array($ext, self::VALID_EXTENSIONS)) {
                return false;
            }

            # this name is composed by the current timestamp and the original name of the file
            // $name = time() . '-' . $file->getClientOriginalName();

            # this name is generated by a unique name using uniqid() function and timestamp
            $name = uniqid() . time();

            $file_name = $name . '.' . $ext;

            // save the file on local storage below the given path
            $file->storeAs($path, $file_name, 'local');

            // return the path of the file from local storage
            return $path . '/' . $file_name;
        }catch(\Exception $e){
            Log::error('Error saving file on local storage: ', [
                'error' => $e->getMessage(),
            ]);
        }
    }

    private function convertToWebp($entry_path): string
    {
        try{
            $old_file = Storage::get($entry_path);
            $path = str_replace('public', 'storage', $this->getDirectory($entry_path)) .'/' . $this->getFileName($entry_path) . '.webp';
            if (Image::make($old_file)->encode('webp', 90)->save($path)) {
                return $path;
            }
            throw new Exception('Error converting image to webp from: ' . $entry_path);
        }catch(\Exception $e){
            Log::error('Error converting image to webp: ', [
                'error' => $e->getMessage(),
            ]);
        }
    }

    private function exists($where, $path): bool
    {
        // exist on storage or s3
        if (Storage::disk($where)->exists($path)) {
            return true;
        }

        return false;
    }

    private function getURL($where, $path): string
    {
        // get url from storage or s3
        if ($where == 's3') {
            return $this->url . $path;
        }

        return Storage::disk($where)->url($path);
    }

    private function getExtension($path): string
    {
        return pathinfo($path, PATHINFO_EXTENSION);
    }

    private function getMimeType($where, $path): string
    {
        // get mime type from storage or s3
        if ($where == 's3') {
            return Storage::disk($where)->mimeType($path);
        }

        return Storage::disk($where)->mimeType($path);
    }

    private function getFileName($path): string
    {
        return pathinfo($path, PATHINFO_FILENAME);
    }

    private function getDirectory($path): string
    {
        return pathinfo($path, PATHINFO_DIRNAME);
    }

    private function getFilePath($where, $path): string
    {
        // get file path from storage or s3
        if ($where == 's3') {
            return $path;
        }

        return Storage::disk($where)->path($path);
    }

}
