export const MODAL_AUTH_SHOW = 'MODAL_AUTH_SHOW';
export const MODAL_AUTH_HIDE = 'MODAL_AUTH_HIDE';

export const MODAL_AUTH_SHOW_SUCCESS_SHOW = 'MODAL_AUTH_SHOW_SUCCESS_SHOW';
export const MODAL_AUTH_SHOW_SUCCESS_HIDE = 'MODAL_AUTH_SHOW_SUCCESS_HIDE';

export const MODAL_PASSWORD_UPDATE_SUCCESS_SHOW = 'MODAL_PASSWORD_UPDATE_SUCCESS_SHOW';
export const MODAL_PASSWORD_UPDATE_SUCCESS_HIDE = 'MODAL_PASSWORD_UPDATE_SUCCESS_HIDE';

export const SET_TOKEN_MODAL_AUTH = 'SET_TOKEN_MODAL_AUTH';