export const MODAL_AUTH_SHOW = 'MODAL_AUTH_SHOW';
export const MODAL_AUTH_HIDE = 'MODAL_AUTH_HIDE';

export const MODAL_AUTH_SHOW_SUCCESS_SHOW = 'MODAL_AUTH_SHOW_SUCCESS_SHOW';
export const MODAL_AUTH_SHOW_SUCCESS_HIDE = 'MODAL_AUTH_SHOW_SUCCESS_HIDE';
