export const MODAL_AUTH_SHOW = "MODAL_AUTH_SHOW";
export const MODAL_AUTH_HIDE = "MODAL_AUTH_HIDE";

export const MODAL_AUTH_SHOW_SUCCESS_SHOW = "MODAL_AUTH_SHOW_SUCCESS_SHOW";
export const MODAL_AUTH_SHOW_SUCCESS_HIDE = "MODAL_AUTH_SHOW_SUCCESS_HIDE";

export const MODAL_PASSWORD_UPDATE_SUCCESS_SHOW =
    "MODAL_PASSWORD_UPDATE_SUCCESS_SHOW";
export const MODAL_CHANGE_STORE = "MODAL_CHANGE_STORE";
export const MODAL_PASSWORD_UPDATE_SUCCESS_HIDE =
    "MODAL_PASSWORD_UPDATE_SUCCESS_HIDE";

export const SET_TOKEN_MODAL_AUTH = "SET_TOKEN_MODAL_AUTH";

export const SET_DIMENSION = "SET_DIMENSION";
export const SET_MODE = "SET_MODE";
export const CHANGE_THEME = "CHANGE_THEME";
export const RECOVER_STORE = "RECOVER_STORE";
