name: Deploy Aws
"on":
  push:
    branches:
      - feature/mySQL
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Aws
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            whoami
